# Generated by Django 3.2.8 on 2021-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='admin', max_length=40),
            preserve_default=False,
        ),
    ]
