# Generated by Django 3.2.8 on 2021-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rename_prirority_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Task', max_length=50),
        ),
    ]
